### ISSUE TITLE
Reference-based signal-level analysis 

### ISSUE THREAD

**Issue by andreyurch** [nanoporetech/remora#105]
Dear developers,

Thank you for the wonderful tool. We recently performed  sequencing of highly damaged DNA and I expect to see specific current traces and significantly increased dwell time in some contexts.  I would like to ask if it is possible to extract a text file with signal-level analysis (probably similar as used for plotting). I need to have in this file at least the following information for each read: chr, position, read_name, kmer (base), current, dwell time. Something similar to the output of nanopolish eventalign (http://simpsonlab.github.io/2015/04/08/eventalign/). 
 It also would be great to additionally explore duplex relationship because we expect to see DNA same only on one of two strands.

**Comment by marcus1487** [comment]
In Remora I've attempted to avoid outputting custom file formats in order to avoid users becoming reliant on a specific format and avoid the inevitable requests for additional data columns. Instead we are aiming to make the Remora API computationally efficient and easy to extract and extend the data for particular uses. The [ipython notebook included in the repo here](https://github.com/nanoporetech/remora/blob/master/notebooks/metrics_api.ipynb) shows how to use the API to extract metrics of interest including a robust estimate of current and dwells. Hopefully that gives you a good start towards extracting the information you need for your analysis. I will try to get a notebook together which outputs an example text file in the next release as I am actually working through the example notebooks right now.
