### ISSUE TITLE
Understanding the output of ```sig_map_refiner.extract_levels()```

### ISSUE THREAD

**Issue by drivenbyentropy** [nanoporetech/remora#111]
Hi, 

I was hoping you could comment on the following issue I am currently trying to understand. When using the ```extract_levels``` function implemented in ```sig_map_refiner``` in order to obtain the expected levels based on the k-mer level table (currently 9-mers), I was expecting the levels of the first and last 4 bases to be undetermined as we are missing the flanking regions for lookup of the center base. However, a call to 

```
sig_map_refiner.extract_levels(util.seq_to_int("AGTGCATGCTAGCTATTACGTAGCTA"))
```

returns

```
array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.0525059 ,  0.53940654, -0.04501047,  0.6269479 ,
        0.15194963, -0.70574003,  0.20513858,  0.72399765,  0.14414866,
        0.84057623,  0.57692546,  0.2476303 ,  0.23250775, -0.94100803,
        0.61526865,  0.06353366, -0.8339354 ,  0.16338404,  0.        ,
        0.        ], dtype=float32)
```

Showing that the first 6, and the last 2 nucleotide levels were not determined. Could you point me in the right direction as to what I am missing here?

Thank you in advance and all the best!

**Comment by marcus1487** [comment]
The k-mer table input into Remora provides a link between a k-mer and expected signal levels. Remora aims to annotate signal to the "appropriate" base in the input sequence. While the appropriate base can be somewhat arbitrary there is generally a maximal information position within the k-mer. In order to identify this maximal information position Remora computes the Kruskal-Wallis test to identify the position within the k-mer with the largest deviation from randomly ordered bases ([see here in the code](https://github.com/nanoporetech/remora/blob/v2.1.3/src/remora/refine_signal_map.py#L201)). This can be visualized in the [Tombo documentation](https://nanoporetech.github.io/tombo/plotting.html#k-mer-signal-levels) as well; note how the dominant position in this figure is position `0` where ACGT are the least randomly ordered. This is logically the "correct" position within the k-mer at which to place the signal assigned to this k-mer. You can see the result of this Krukal-Willis test in the log output of Remora each time the k-mer table is loaded.

**Comment by drivenbyentropy** [comment]
Thank you @marcus1487 for the explanation. I have wondered what the ```determine_dominant_pos``` function does for quite some time. This makes perfect sense now.
