### ISSUE TITLE
Clarification on the interplay between ```reverse_signal``` and ```ref_anchored```

### ISSUE THREAD

**Issue by drivenbyentropy** [nanoporetech/remora#114]
@marcus1487, I was hoping I could get your input on the following topic:

When calling instantiating an ```io_read``` using ```from_pod5_and_alignment()``` (either directly or via ```get_io_reads()```) for bam records mapping to the negative strand, what is the default orientation of the resulting ```io_read``` (i.e. with ```reverse_signal=False```)? My hunch, based on looking at the source code of the plotting functions in ```io.py``` and the [metrics API notebook](https://github.com/nanoporetech/remora/blob/master/notebooks/metrics_api.ipynb), I suspect that signal and sequence will always be 3' to 5' oriented but I would like to make certain my understanding is correct. 

Furthermore, (assume signal refinement with ```ref_mapping=True``` has been performed)  when calling the ```compute_per_base_metric()``` method for these reads with ```ref_anchored=True```, does this reverse the orientation of the resulting metrics? I.e. do I have to manually reverse the metric array again in order to obtain 3' to 5' orientation? This does appear to be the case in ```get_ref_reg_sample_metrics()``` [here](https://github.com/nanoporetech/remora/blob/8f4d61705f0304894b0da955439db52c48690a5a/src/remora/io.py#L739).

Thank you in advance and all the best!

**Comment by marcus1487** [comment]
The `reverse_signal` option is only for RNA data. I've not called the option RNA in order to future proof against the potential release of 5' to 3' sequencing RNA kits or 3' to 5' sequencing DNA kits; though neither of these are planned or particularly likely in the immediate future. Thus the `reverse_signal` options should be ignored for all DNA samples.

For the second point I am actually working on the notebooks to help clarify these points. I'll post some screenshots here that will be included in the next release (Remora 3.0) coming quite soon. The io.Read API is largely the same with some feature additions in the next version so these screenshots should help with your questions.

<img width="977" alt="image" src="https://github.com/nanoporetech/remora/assets/13755444/504c56d9-92a9-4975-98fe-8f8028e77973">

<img width="966" alt="image" src="https://github.com/nanoporetech/remora/assets/13755444/fe8e48d2-da1a-4a0f-a37b-d74cbd7ec0b1">

<img width="942" alt="image" src="https://github.com/nanoporetech/remora/assets/13755444/0e2bfb7d-3683-4935-a698-32f70e711ce0">

**Comment by drivenbyentropy** [comment]
@marcus1487 As always, your answer is right on point! Thank you and I am looking forward to the next release.
