### ISSUE TITLE
Alternative mapper to produce input bam for e.g. model training 

### ISSUE THREAD

**Issue by schriwag** [nanoporetech/remora#121]
Hi, 

I have a question regarding the use of an alternative mapper like graphmap for preprocessing of data fed into remora. 

Basecalling/mapping with dorado, which uses minimap2 internally, with --emit-moves would give me the bam with move table and MD tag for e.g. training of a new model. However, I have the specific case in which minimap2 is not really able to map my reads even with parameter tweaking, therefore I usually use graphmap for mapping. I'm not sure how to preprocess the data now with graphmap to end up with a remora compatible bam file. Would it be possible to basecall with dorado, map with graphmap and add the move table somehow to the graphmap bam output? 

Thank you! 
Anja

**Comment by marcus1487** [comment]
It looks like GATK have a potential solution [here](https://gatk.broadinstitute.org/hc/en-us/articles/5358868598299-TransferReadTags-EXPERIMENTAL-). This is listed as experimental though. My next solution would be to perform these operations in a custom script with pysam. The `remora.io.ReadIndexedBam` object may help in order to load the move tables from the original read records without storing them all in RAM.

**Comment by schriwag** [comment]
Thank you for the suggestions! I will try it out.
