### ISSUE TITLE
The difference between signal value “trimmean” and “dwell"

### ISSUE THREAD

**Issue by Taojianchang** [nanoporetech/remora#122]
Hi,

Could you please give an explanation about the difference between signal value “trimmean” and “dwell”.  Is the value "trimmean” calculated after rescaling or base trimming? Can I use “dwell” to compare signal difference in  potential modified bases ?

Thank you !
Jianchang

**Comment by marcus1487** [comment]
`trimmean` is the mean of the normalized signal current assigned to a base with the two signal points near the edge of the base trimmed off (removed from the mean computation). The simpler `mean` metric computes the mean of the normalized signal current values without this trimming. The trimmed values can often be more robust since the signal points at the transition between two bases can often be between the two bases.

The `dwell` metric is the integer number of signal points assigned to a base. This can certainly be used to identify potentially modified bases.
