### ISSUE TITLE
--basecall-anchor overrides --focus-reference-positions in dataset prepare

### ISSUE THREAD

**Issue by andrewgalbraith21** [nanoporetech/remora#137]
Hello!

I noticed that when running remora dataset prepare --basecall-anchor seems to override --focus-reference-positions. Regardless of the bed file I input into --focus-reference-positions, it does not change my training dataset when --basecall-anchor is enabled. I assume this is the intended functionality however, I was wondering if maybe these parameters could work in tandem. For instance, I am hoping to train on only correctly basecalled contexts which are limited to a specific range of regions in the reference. Let me know if there is a way to do this and please notify me if I am misunderstanding anything. Thanks so much!

All the best,
Andrew Galbraith

**Comment by marcus1487** [comment]
These arguments should indeed work in tandem. Could you explain exactly how you are verifying that the training data is unchanged when the `--focus-reference-positions`?

Note that "correctly basecalled contexts" is controlled by the `--motif` argument and not the  `--basecall-anchor`, `--focus-reference-positions` arguments. In order to a basecall anchored chunk to be selected at a focus reference position, the canonical base must match, but the larger context does not need to match (unless the motif argument is also specified). To help follow the expected logic exactly this is the function controlling the focus position determination with the set of option specified. https://github.com/nanoporetech/remora/blob/v3.0.0/src/remora/io.py#L2107 I hope this helps, but please do post any further questions.

**Comment by andrewgalbraith21** [comment]
Hello @marcus1487, good to know. It was likely a coincidence that --focus-reference-positions did not alter my dataset on the few use cases I looked at.
