### ISSUE TITLE
R10.4 settings recommendations

### ISSUE THREAD

**Issue by pwh124** [nanoporetech/remora#14]
Hello!

I am interested in training a model on R10.4 modified data.

In the README, which uses a R9.4 model as an example, the following suggestions are made for running `remora dataset prepare`:
``` 
--chunk-context 50 50 
--kmer-context-bases 6 6
```
Would this be different for R10.4?

Thanks!
Paul

**Comment by marcus1487** [comment]
All released models use the `--chunk-context 50 50` setting. The `--kmer-context-bases 6 6` setting is actually inaccurate for the released models. This is set at data preparation, but can be adjusted at training time (due to data storage type trimming k-mer context is simple, but changing chunk context is not trivial). At the `remora model train` step all released models have the `--kmer-context-bases 4 4` setting. I will update the docs with commands to obtain the highest accuracy models.

**Comment by pwh124** [comment]
thanks marcus!
