### ISSUE TITLE
How do I acheive Re-squiggling with Remora

### ISSUE THREAD

**Issue by alexturcoo** [nanoporetech/remora#156]
Hello, I am developing a pipeline to basecall raw ONT current data (in Fast5 format). In much of the literature I have read, preprocessing occurs in 2 steps. FIrst, the raw reads are basecalled and then, the basecalled reads, along with a reference genome and the raw current values are re-squiggled to correct for spurious variation. In my workflow, I am using Dorado to basecall the raw reads. The next part of my workflow (resquiggling the basecalled reads) I am struggling with. How can I utilize remora to acheive re-squiggling of the basecalled reads from dorado, similar to the way Tombo's re-squiggling command works. Tombo segmentation provides current measurements at the base level, which is the data I am interested in getting. Is it possible to acheive this using remora?

EDIT: signal mapping refinement in Remora is the new re-squggling. But in Tombo you were able to use a reference genome as well, where is the reference genome included in this step for remora. Do you need to align raw basecalls to a reference genome prior to using remora for signal mapping refinement?

**Comment by marcus1487** [comment]
To answer the second part, yes signal mapping refinement is the new re-squiggling as I believe re-squiggle may have taken on a couple of different meanings to different groups. Signal mapping refinement is adjusting the alignment between signal and sequence to more closely match a set of expected levels from the input sequence.

In order to map to the reference genome, yes the reads input into Remora should be aligned. See the full tutorial for applying signal mapping refinement and reference anchoring in the `notebooks` section of this repository.

**Comment by marcus1487** [comment]
Below the third cell in the metrics notebook the metrics are defined. You can see there that the dwell metric is defined as "Number of sample points assigned to a base.".
