### ISSUE TITLE
Missing MD Tag Despite Being Able to See MD Tag in BAM File

### ISSUE THREAD

**Issue by VBHarrisN** [nanoporetech/remora#160]
While trying to create a new Remora dataset using the remora dataset prepare command, we get the "missing MD tag" error thrown every time. However, we are using a BAM file created by Dorado WITH the --emit-moves tag included. Furthermore, we used samtools to find the :MD:Z: tag within our BAM file and we found Multiple MD tags. We thought we might be running out of memory, preventing Remora from ever reaching the MD tag, but the first MD tag is on line 6, and running the command using 32 GB of memory did not change the outcome.

**Comment by VBHerrenC** [comment]
Having the same issue! Let me know if you find anything.

**Comment by marcus1487** [comment]
Can you describe your detail in a bit more detail? Specifically you mention that you "get the "missing MD tag" error thrown every time". Do you mean that every time you run Remora this failed read reason is shown? Or that all reads processed fall into the "missing MD tag" failed read mode. Given that you have many reads without MD tags (including unmapped reads), it is expected that these reads will fail due to the "missing MD tag" reason, but the other reads should be processed successfully. Are you getting no reads successfully processed for the run?

**Comment by VBHarrisN** [comment]
Here is the output:
(venv3) (base):~/RNA_Mod_Train$ remora dataset prepare data.pod5 dorado_single_sup_train_convert.bam --mod-base-control --refine-kmer-level-table 9mer_levels_v1.txt --refine-rough-rescale --reverse-signal --num-reads 500
Indexing BAM by read id: 4140 Reads [00:00, 36532.06 Reads/s]
[11:03:25] Extracting read IDs from POD5
[11:03:25] Found 4134 BAM records, 4000 POD5 reads, and 3906 in common
[11:03:25] Making reference-anchored training data
[11:03:25] Allocating memory for output tensors
[11:03:25] Processing reads
Extracting chunks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:00<00:00, 862.87 Reads/s]
[11:03:25] Unsuccessful read/chunk reasons:
    249 : No reference sequence (missing MD tag)
      2 : Chunk sequence too long to store
[11:03:26] Extracted 3763 chunks from 500 reads.
[11:03:26] Label distribution: Counter({0: 3763})

**Comment by marcus1487** [comment]
This looks like a successful remora dataset preparation run. You have 500 total reads processed and 249 of the reads do not contain the MD tag. It sounds like you are expecting many reads which do not contain the MD tag, many reads failing for this reason is completely expected. This does not mean that the run has failed, but instead that 249 reads will not produce Remora training chunks as they do not contain MD tags.
