### ISSUE TITLE
writing the signal alignment to an output file in SAM format using auxiliary tag 'ss'

### ISSUE THREAD

**Issue by hiruna72** [nanoporetech/remora#169]
Hey,

My problem ties back to this thread by @marcus1487 on GitHub (https://github.com/nanoporetech/remora/issues/145#issuecomment-1861167122).

I'm exploring signal-to-sequence alignment with remora and considering using squigualiser (https://github.com/hiruna72/squigualiser) to visualize the alignments. 
It'd be really helpful if you could consider outputting the event alignment in the 'ss' format to a SAM file as described here: https://hasindu2008.github.io/f5c/docs/output#ss-tag.

Thank you!

**Comment by marcus1487** [comment]
Signal alignment is never output by Remora, but instead only available via the API and used within the code before being disposed of without explicitly writing the signal alignment to disk. This was an intentional choice as there are many issues with storing and retrieving signal alignment data from disk. For example, signal alignment can be made against the basecalls or the reference sequence, so either could be "stored" in the output format, thus requiring metadata corresponding to the source of the signal alignment.

Since Remora does not support any output of signal alignment to a format on disk, I would recommend that the Remora API be used in order to convert to the ss-tag and append this to the bam record before writing back out to disk. I realize that this pushes the development effort onto the user, but I don't think that I would like to support signal alignment output directly in the Remora ecosystem.
