### ISSUE TITLE
Resquiggle

### ISSUE THREAD

**Issue by MarioRinBarr** [nanoporetech/remora#174]
Hello,

I have a doubt with the use of remora. I want to make a resquiggling, similar to what can be done with Tombo, to use it in other programs. However, I don't see a function similar to this, even though Remora is supposed to replace this program. Am I missing something in the documentation?

Thank you very much

**Comment by marcus1487** [comment]
High level documentation can be found [here](https://github.com/nanoporetech/remora?tab=readme-ov-file#python-api-and-raw-signal-analysis). And deeper documentation on raw signal analysis is found in the notebooks directory of the repository.

**Comment by MarioRinBarr** [comment]
Thank you for your response. If I understand correctly, and from the results obtained with the test files, remora analyze plot ref_region plots the signal in a pdf, but does not create a file with the resquiggled events, isn't it? I don't see any option to get such a file.

**Comment by marcus1487** [comment]
That is correct. It was an intentional choice to avoid a file format as the output of the Remora re-squiggle algorithms. At the end of the metrics API notebook an example of text output is given, but it is left up to the user to decide which metrics and what associated data can be output to file. I've found that directly providing a file format leads to a bloated file when users request additional metrics or types of resquiggling procedures, eventually making the file format hard to use effectively. I hope that this snippet might suffice for your use case, but please post if there is a specific reason that a command line interface for a text output would be required.

**Comment by Toinax** [comment]
Hi @marcus1487 ,
Thanks for your response, but it is still unclear to me.

To perform a re-squiggle on fast5 files, using fastq as Tombo allowed us to do, we can just run a "plot ref_region" on our data ?

Or it is much more complicated than that ?

I'm trying to run Deepsignal, that needs a re-squiggle before the extraction of the features for nanopore data. But since Tombo is deprecated, i'm trying to use Remora instead.
