### ISSUE TITLE
io_read.seq, ref_seq and signal orientation for revserse mapping

### ISSUE THREAD

**Issue by yuxinPenny** [nanoporetech/remora#178]
Dear authors of Remora,

I am trying to extract features from basecalls (io_read.seq), reference sequence (io_read.ref_seq) and signals from the io_read object generated from pod5 and bam.

I am confused about the orientation of those features for reads mapped to minus strand. Shall I reverse some of them to make them in the same orientation.

I would appreciate if you can help!

**Comment by marcus1487** [comment]
All information in an `io.Read` object is "read-oriented". This is anchored to the basecalled sequence in 5' to 3' direction. So for a minus strand mapped read the ref_seq will be the reverse complement of the sequence found in the reference FASTA file. This corresponds to the 5' to 3' signal as well. So for RNA reads which are read in 3' to 5' direction the io.Read signal will be flipped from the POD5 storage format. This format allows the easiest extraction of training examples which is the primary target of the Remora repo. I hope this helps clarify a bit, and please respond if further clarification is required.

**Comment by yuxinPenny** [comment]
Thanks!

So, do we need to determine the direction of RNA reads (5' to 3' or 3' to 5') by ourselves and flip the signal manually?

**Comment by yuxinPenny** [comment]
Thanks!

So, do we need to determine the direction of RNA reads (5' to 3' or 3' to 5') by ourselves and flip the signal manually?

**Comment by marcus1487** [comment]
It depends on the goal of your analysis. There is an attribute, `reverse_signal`, which indicates if the read signal has been processed as 3' to 5' signal. If you can detail your analysis goals u can help figure out if you need to reverse certain arrays associated with an io.Read object.

**Comment by wangziyuan66** [comment]
Hi Marcus,

I wonder if I need to modify the parameter sd_params (4,3,0.5) for RNA DTW after reverse_signal=True. 

Best

**Comment by marcus1487** [comment]
We have found that these values are relatively robust to RNA or DNA data, but certainly can have some effect on certain mappings.  It is not necessary to change these values to get reasonable results.

**Comment by wangziyuan66** [comment]
Hi,

Thanks for your reply! I still have two questions. For Remora modification calling and visualization, both of them relied on kmer model. However, for the same context, a modification site will correspond to different signal level. My question is that will this affect the visualization of signal, for I found in the modification area the dwell time for one base is really short. I do not know whether this is caused by DTW process for the kmer model is only canonical bases. My second question is that which parameters for remora data prepare should use for signal refine, should I use kmer model to refine? Or just leave it and use the initial movetable. 

Best

**Comment by marcus1487** [comment]
> I do not know whether this is caused by DTW process for the kmer model is only canonical bases

The signal assignment around a modified base will indeed deviate from the expected levels given canonical sequence. This may indeed result in "poor" alignment to the expected signal levels. Methods to estimate the expected levels while also aligning to them are beyond the scope of Remora. Remora is intended to give a reasonable alignment in most regions and enable further downstream research. Estimation of signal levels and characteristics around novel bases is left to the exploration of the researcher. 

Due to the fact that signal alignments are not robust around modified bases all production remora modified base models use the k-mer table only to adjust the signal scaling (the `--refine-rough-rescale` option for data prep command). The signal refinement is intended primarily for the signal visualization portion of the remora API. If you were to plot signal without refining the signal mapping it would be very hard to gain meaningful insights based on statistics from the assigned sections of each read. The neural networks can indeed handle this fuzzy assignment from the basecaller move table (not entirely an expected result). 

I hope this helps in understanding the use of the k-mer table in Remora. Please post if further clarification would be helpful.
