### ISSUE TITLE
How to do a Tombo resquiggle with Remora ?

### ISSUE THREAD

**Issue by Toinax** [nanoporetech/remora#187]
That is correct. It was an intentional choice to avoid a file format as the output of the Remora re-squiggle algorithms. At the end of the metrics API notebook an example of text output is given, but it is left up to the user to decide which metrics and what associated data can be output to file. I've found that directly providing a file format leads to a bloated file when users request additional metrics or types of resquiggling procedures, eventually making the file format hard to use effectively. I hope that this snippet might suffice for your use case, but please post if there is a specific reason that a command line interface for a text output would be required.

_Originally posted by @marcus1487 in https://github.com/nanoporetech/remora/issues/174#issuecomment-2129623980_

Hi @marcus1487 ,
Thanks for your response, but it is still unclear to me.

To perform a re-squiggle on fast5 files, using fastq as Tombo allowed us to do, we can just run a "plot ref_region" on our data ?

Or it is much more complicated than that ?

I'm trying to run Deepsignal, that needs a re-squiggle before the extraction of the features for nanopore data. But since Tombo is deprecated, i'm trying to use Remora instead.

**Comment by marcus1487** [comment]
The pipeline required to support the re-squiggle format within a file format was not sustainable. It is unfortunate that this does indeed make several downstream tools which depended upon this format unsupported as well. There were simply too many issues with the storage of the re-squiggle results back into the signal single-FAST5 format. Namely there was no way to store results for multiple mappings (or multiple results with different hyper-paramters) and this process often corrupted some portion of the signal files.

I realize that it is a large amount of development work to convert Deepsignal to directly use the new Remora re-squiggle API, but that is unfortunately the best option with currently supported software. 

In order to run reference anchored signal plotting the `remora analyze plot ref_region` is supplied. But note that the re-sqiuggle results which went into this plot are not saved in any output format.

**Comment by marcus1487** [comment]
Remora will not support writing back to single FAST5 files, so I am closing this issue.
