### ISSUE TITLE
Suggested coverage for model training

### ISSUE THREAD

**Issue by mvolar** [nanoporetech/remora#52]
Hello,
I am running some tests and since I fail to find recommendations in the documentation regarding the Remora training module, I was wondering what is some tried/tested recommended genome coverage for canonical(pcr-treated)/modified basecall testing? We are now sitting at around 50x and were wondering if we need to perform additional sequencing experiments in order to properly train our models.

**Comment by marcus1487** [comment]
Ironically for modified base training lower coverage over a larger reference is recommended. In particular a larger sequence context around any fixed context is ideal. It is also ideal to have matched coverage between canonical and modified training chunks. This will allow the model to learn the difference in signal due to the modified base and not memorize sequence context for modified or canonical training examples.

For the total training dataset size, we use 60 million total chunks for production models. You can get very good results with 5-10M total chunks. 

Hopefully this helps, but please post if further clarification would help.

**Comment by mvolar** [comment]
Thank you very much for your response. I would just like some clarification on how to exactly calculate number of chunks (i.e. default chunk size of the training preprocessing) that I have available?

I see from the code that chunk size is defined as a tuple (50,50) which I presume is signal length which is variable in it's mapping to real number of bases, but do you have any ballpark to help us estimate? We would also like to know this since we still have a sample to train and if we could avoid any additional sequencing we would be grateful. Our genome is 200mb.

 Also, would you recommend extending or contracting that chunk size context depending on higher/lower coverage?

**Comment by marcus1487** [comment]
I think there may be some confusion here on the definition of a chunk and how this related to chunk size. A Remora chunk (training unit) is defined in the beginning of the README in the "Getting Started" section. Chunks are fixed signal length (default 50 signal points before and after the chunk center), so it is correct that this will include a variable number of bases in each training chunks. This is a separate issue from the number of chunks recommended. I would recommend to stick with the default chunk size no matter the coverage as input. These values are largely unrelated. No matter the defined parameters for each chunk I would recommend 60 million chunks for training.
