### ISSUE TITLE
read length for model training

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/remora#73]
Hi @marcus1487 ,
Since nanopore reads has various length, does remora prefer specific read length for model training? Could you suggest a rough range for the best training performance? 
Thanks,

**Comment by marcus1487** [comment]
There is not necessarily an optimal length for modified base model training data. I would say the best rule of thumb is that training data matched as closely as possible to the target application data is optimal. That being said, it is likely that anything over 1kb is likely not to change much and we have seen that randomer training data (~150 bases) can generalize to very long reads. I hope this helps a bit. Please reach out with any further questions.

**Comment by Yijun-Tian** [comment]
Thanks, @marcus1487. This week, I used the WGA reactions with dmATP to generate the 6mA positive control. Seems the WGA DNA library is a pore killer, and the data yield is not very good. The model is not ideal to separate the positive and negative. Thanks for clarifying the read length issue. Maybe can use some random oligos with A in the center to ligate into 1kb reads for training.

**Comment by marcus1487** [comment]
For the WGA strategy, was this a 100% modified base 6mA positive control? If so the recently released 6mA all-context model is not targeted to this sample type. 100% modified base samples are not generally a great positive control as they do not represent the type of signals generally seen in target samples (biological or otherwise). If there is an application requiring differentiation of 100% 6mA vs 100% canonical A then this sample may be useful as a control. Otherwise I would suggest a validation sample more closely matched to your intended target.

For questions on random oligos, we have set up a developer release repository, Betta, and I would be more than happy to go over details for these samples there. Please see this post for instructions on accessing this repository: https://community.nanoporetech.com/posts/betta-tool-release
