### ISSUE TITLE
Support for legacy kmer level tables

### ISSUE THREAD

**Issue by CodingKaiser** [nanoporetech/remora#75]
With the newer versions of remora, it appears refining models by providing kmer level tables is recommended. However, it appears that currently only the newer formats are supported. Providing a legacy tables's 6-column format with headers results in an error. Are there plans to support these legacy formats in the future?

[https://github.com/nanoporetech/kmer_models/tree/master/legacy](https://github.com/nanoporetech/kmer_models/tree/master/legacy)

**Comment by CodingKaiser** [comment]
We have a few r9.4.1 DNA runs on which we would like to perform model training, but the increased accuracy promised through use of the level tables is not super important for our purposes at the moment. Would you mind sharing the one-liner for conversion to the new format? Are you simply taking the level mean from the legacy format and using that to calculte the expected level with 0-mean and unit variance?

**Comment by marcus1487** [comment]
The mean-0 and unit variance conversion will be done in Remora, so this conversion is not necessary in order to use a model with Remora. The release models perform this conversion upfront before storage for simplicity in workflows and error checking. 

Thus you can convert to the simpler level mean table with the following one-liner: `awk 'NR > 1 {print $1"\t"$2}' legacy/legacy_r9.4_180mv_450bps_6mer/template_median68pA.model > legacy/legacy_r9.4_180mv_450bps_6mer/level_table.txt`
