### ISSUE TITLE
Mixing data from different runs for training

### ISSUE THREAD

**Issue by drivenbyentropy** [nanoporetech/remora#80]
Hi, 

I was wondering if we can safely mix data obtained from two different sequencing runs to create training sets. Specifically, we sequenced each, treated and untreated sample, twice but the second run was performed with a lower sequencing speed compared to the first one. Is it OK to mix these or should we rather train two independent models for each case?

Thanks!

**Comment by marcus1487** [comment]
This is "safe" in terms of Remora functionality, though is generally not recommended. A Remora model will generally perform best trained on the target data type. If you intend to apply the model to varied conditions I would recommend training separate models to the specific conditions. 

If condition types must be merged I would highly recommend balancing the dataset along the condition (sequencing speed) and labels (canonical or modified). Any imbalance here could result in the model "associating" the condition with the label.

I hope this helps and do please reach out with any further questions.

**Comment by jorisbalc** [comment]
I would like to ask a question regarding to this topic aswell:

For the purpose of model training. Would running the modified samples and canon sequences during different sequencing runs have any impact on the model training itself? We would like to experiment with this since it's pretty difficult to acquire modified sequence data for our project and by doing so we tend to acquire as much data as possible from a sample.

**Comment by marcus1487** [comment]
We have found success internally training models with flowcells containing only a single sample.
