### ISSUE TITLE
Remora mod model for guppy

### ISSUE THREAD

**Issue by vahidAK** [nanoporetech/remora#88]
Hi there,

I was wondering if we train a modbase model using remora, can we use this model with Guppy for modification calling?

Thanks,
Vahid

**Comment by marcus1487** [comment]
Dorado is the current recommendation for exporting and running Remora models. Dorado compatible models are the default of the `remora model export command.` Guppy export is available in the [scripts directory](https://github.com/nanoporetech/remora/blob/master/scripts/convert_ts_to_ont_json.py), but will likely be removed in a release in the near future.

**Comment by vahidAK** [comment]
Thanks

**Comment by jorisbalc** [comment]
I've been using bonito to run remora models, but seeing this issue, I attempted to export the model in ts for use in dorado. However, it seems that dorado does not accept the ts model giving the following error while providing the model to the dorado basecaller command line as `--modified-bases-model`: 
_toml::parse: file open error -> test_model_1.12/config.toml_

my full command line is as follows:
`dorado basecaller --modified-bases-model test_model_1.12 --reference gm119_assembly.fasta /home/v313/Dorado/bin/dna_r10.4.1_e8.2_400bps_sup@v4.2.0/ gm119_mod_reads.pod5 > mod_calls_gm119.bam`

Am I missing something? Would prefer using dorado over bonito, since it's way faster on our machine. Thanks in advance!
